# Generated by Django 3.0.3 on 2020-02-27 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='导航主题')),
            ],
            options={
                'verbose_name': '导航主题',
                'verbose_name_plural': '导航主题',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='分类主题')),
                ('big_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.BigTopic')),
            ],
            options={
                'verbose_name': '分类主题',
                'verbose_name_plural': '分类主题',
            },
        ),
    ]
