# Generated by Django 3.0.3 on 2020-02-28 16:51

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=slugger.fields.AutoSlugField(populate_from='title', unique=True, verbose_name='简短标识'),
        ),
    ]
